package com.github.ipan97.java.multithreading;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.github.ipan97.java.multithreading.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
